[package]
name = "resolver"
version = "0.2.10-alpha.6"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
semver = { version = "1.0", features = ["serde"] }
anyhow = "1.0"
reqwest = { version = "0.13", features = ["json", "rustls", "rustls-native-certs"] }
tokio = { version = "1.52", features = ["full"] }
serde_yml = "0.0.12"
serde_json = "1.0"
dirs = "6.0"
futures = "0.3"
