[package]
name = "kumo-core"
version = "0.2.10-alpha.17"
edition = "2021"

[dependencies]
blake3 = "1.8"
tokio = { version = "1.52", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
walkdir = "2.4"
tar = "0.4"
flate2 = "1.1"
dirs = "6.0"
reqwest = { version = "0.13", features = ["json", "rustls", "rustls-native-certs", "stream"] }
futures-util = "0.3"
tempfile = "3.10"
tokio-util = { version = "0.7", features = ["io", "io-util"] }
bytes = "1.11"
reflink-copy = "0.1"
sha1 = "0.11"
