name: Tests

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  message:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Auto-Answer
        uses: jmaxdev/automatic-answer@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN || '' }}
          use_personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN != '' }}

  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Kumo
        run: cargo check

        
      
      