name: Issues

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  message:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Auto-Answer
        uses: jmaxdev/automatic-answer@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN || '' }}
          use_personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN != '' }}
